version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-management-api
    restart: unless-stopped
    environment:
      ENV: docker
      ENV_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vehicle_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:17-alpine
    container_name: vehicle-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vehicle_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vehicle_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vehicle-management-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
